# scratch/verify_llms.py
# Tests the multi-provider LLM fallback logic locally.

import os
import sys
from dotenv import load_dotenv

# Add Middleware to path to import services
sys.path.append(os.path.join(os.path.dirname(__file__), "..", "Middleware"))
from services.llm_service import generate_incident_report

load_dotenv()

def test_flow():
    print("--- LLM Integrated Flow Verification ---")
    
    # Dummy data
    channel = "A-1 (Power System)"
    score = 0.95
    anomaly_count = 190
    total_windows = 190
    threshold = 0.5
    device = "cuda"
    
    print(f"Testing report generation for {channel} (Severity: CRITICAL)...")
    
    report = generate_incident_report(
        channel, score, anomaly_count, total_windows, threshold, device
    )
    
    print("\nGenerated Report:\n" + "="*40)
    print(report)
    print("="*40)
    
    if "INCIDENT REPORT — Channel" in report and "exceeding threshold" in report:
        print("\nNote: Fallback static template was used (likely because no API keys or local Ollama are detected).")
    else:
        print("\nSuccess: Report generated by an LLM provider!")

if __name__ == "__main__":
    test_flow()
